#!/usr/bin/env bash


help(){
    cat<<__EOF__
    usage: m info [ help ]

    Examples:
      m info          #  print macOS product version information
      m info basic    #  print macOs operating basic system version information
      m info detailed #  print macOs operating detailed system version information

__EOF__
}

case $1 in
    detailed)
        system_profiler -detailLevel full SPSoftwareDataType
        ;;
    basic)
        system_profiler -detailLevel mini SPSoftwareDataType
        ;;
    help)
        help
        ;;
    *)
        sw_vers
        ;;
esac

# vim: ts=4 sw=4 softtabstop=4 expandtab
